language: node_js
node_js: "10"

git:
  depth: 3

cache:
  yarn: true
  directories:
    - node_modules

## Install dependencies.
install: yarn install

## Run build script.
script: yarn build

## Deploy to branch "gh-pages".
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    local-dir: ./dist/
    target-branch: gh-pages
    github-token: $GH_TOKEN
    on:
      branch: master

